# Propriedades da aplicação Spring Boot
spring:
  main:
    banner-mode: 'console'
  http:
    encoding:
      charset: "@project.build.sourceEncoding@"
  application:
    name: "@project.name@"
    version: "@project.version@"
    description: "@project.description@"

# Dados exibidos no endpoint "info" do Actuator
info:
  app:
   stack-depth: 999 # Profundide máxima das stack traces que serão escritas nos logs
   stack-size: 99999
   name: "@project.name@"
   version: "@project.version@"
   description: "@project.description@"

# Porta do servidor
server:
  port: 8080

# Logging
# Sobrescrevendo grupos e níveis de log
logging:
  group:
    web: org.springframework.core.codec, org.springframework.http, org.springframework.web
    spring: org.springframework.core.env
    servlet: org.springframework.boot.web, org.apache.catalina, org.apache.coyote, org.apache.tomcat
    data: org.springframework.jdbc.core, org.hibernate.sql, org.springframework.orm.jpa, com.zaxxer.hikari, org.hibernate, org.jooq.tools.LoggerListener
    app: br.com.rifesil.fique.em.casa.tic.tac.toe
  level:
    root: INFO
    spring: INFO
    app: DEBUG
    servlet: WARN
    web: WARN
    data: INFO
